// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dtos

import (
	"errors"
)

var ErrEnumValueMustBeString = errors.New("enum values must be string")

const (
	RoleAdmin Role = "ADMIN"

	RoleOrdinary Role = "ORDINARY"
)

type Role string

func (v Role) String() string { return string(v) }

func (e *Role) UnmarshalGQL(v any) error {
	s, ok := v.(string)
	if !ok {
		return ErrEnumValueMustBeString
	}
	*e = Role(s)
	return nil
}
