package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/aereal/enjoy-gqlgen/dtos"
	"github.com/aereal/enjoy-gqlgen/executableschema"
)

func (r *queryResolver) User(ctx context.Context, name string) (*dtos.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

func (r *Resolver) Query() executableschema.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
